name: "PR Auto Assign And Review"
on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
          echo "pnpm_cache_dir=$(pnpm store path)" >> $env:GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Generate config
        run: |
          touch .env.vault
          echo GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} >> .env.vault
          node ./scripts/generateAutoAssignConfig.cjs

      - uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: ".github/auto_assign.yml"
