name: PR Docs Build

on:
  pull_request:
    paths:
        - "docs/**/*"
        - "package.json"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.node-name }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18]
        os: [ubuntu-latest, windows-latest]
        include:
          - node-version: 18
            node-name: LTS
          - node-version: 18
            node-name: Current

      fail-fast: false

    env:
      PULL_REQUEST_NUMBER: ${{ github.event.number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn store directory
        id: yarn-cache
        run: |
          echo "yarn_cache_dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
          echo "yarn_cache_dir=$(yarn cache dir)" >> $env:GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup yarn cache
        with:
          path: ${{ steps.yarn-cache.outputs.yarn_cache_dir }}
          key: ${{ runner.os }}-yarn-store-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-store-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build common utils
        run: yarn run build
        env:
          FORCE_COLOR: 2
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Build website
        run: yarn run docs:build
        env:
          DOC_ENV: preview
          NODE_OPTIONS: --max-old-space-size=4096

      # share website dist
      - name: Upload artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: docs-dist
          path: docs/.vitepress/dist/
          retention-days: 1

      # write pr.txt for share
      - name: Save pr number
        if: matrix.os == 'ubuntu-latest'
        run: echo ${PULL_REQUEST_NUMBER} > ./pr.txt

      # share pr number
      - name: Upload pr number
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: pr
          path: ./pr.txt
          retention-days: 1
