name: Publish Docs Deploy

on:
  workflow_run:
    workflows: ["Publish to NPM registry"]
    types: [completed]
  workflow_dispatch:
    inputs:
      deployNotes:
        description: "手动触发文档部署不会生成新的 release"
        required: true
        type: boolean

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          persist-credentials: false

      - name: Start Netlify Build
        run: curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOKS }}
