name: Publish Docs Deploy

on:
  workflow_run:
    workflows: ["Publish to NPM registry"]
    types: [completed]
  push:
    branches:
      - main
    paths:
      - "docs/**/*"
      - "package.json"
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          persist-credentials: false

      - name: Start Netlify Build
        run: curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOKS }}
