name: Publish Docs Deploy

on:
  workflow_run:
    workflows: ["Publish to NPM registry"]
    types: [completed]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          persist-credentials: false

      - name: Start Netlify Build
        run: curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOKS }}
